### ISSUE TITLE
Refactor to Remove Code Smells (Long Method, Hardcoding)

### ISSUE THREAD

**Issue by leenlab2** [TLI-group3/TLI-server#42]
## Suggested Changes
- [x] Refactor the InterestFilter file to shorten the `getBestfiveCars` method
- [x] Change hardcoded quantities into global variables
- [x] Remove shared and repeated code related to the AccountHolder somewhere else (for example, into the AccountHolder entity)
- [x] Get rid of repetition in the database access methods

**Comment by Alamgir-K** [comment]
With the latest PR merge, every one of these issues is fixed.
